// Shared product catalog for Jewels by Laiba
const products = [
            { id: 1, title: 'Stainless Steel Magnet Flower Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1Zpj2NwsDH3780eVkafI9T7zNY_N9eVeL&sz=w800' },
            { id: 2, title: 'Stainless Steel Flower Studs', price: 500, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1GKDY6QFXYR4VedezsVCGN3_dZ8sKe4lK&sz=w800' },
            { id: 3, title: 'Fancy Earrings', price: 450, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1OutDZKeQXumOLxoo28CS2C-0FoYeKdmn&sz=w800' },
            { id: 4, title: 'Stainless Steel Resin Studs 1 Pair', price: 600, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1PzT70p5nznze99f1NFH6JskGbS_xeN4g&sz=w800' },
            { id: 5, title: 'Stainless Steel Resin Flower Studs', price: 600, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1pVBq4dGTOgXFZCxOvMFH5pze2KufmVWY&sz=w800' },
            { id: 6, title: 'Stainless Steel Resin Heart Studs', price: 600, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1HWgsebiZS7UH4Jrfp-u4izBLOmZoBjGl&sz=w800' },
            { id: 7, title: 'Stainless Steel Studs', price: 500, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1CizyQE7ZFiXIKSgX5ujTUgT3R-etE4dd&sz=w800' },
            { id: 8, title: 'Stainless Steel Double Ball Chain Necklace', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1hLXWxUnfJ2pTGUMsY0i2mwyx2BaHrVzP&sz=w800' },
            { id: 9, title: 'Stainless Steel Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1b9YsdQlMyCbzqy3RIWhlB0vKua5Uswp7&sz=w800' },
            { id: 10, title: 'Stainless Steel Star Pendant', price: 600, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1nYyQM6b939_BHhGHB85lmv7j6dkD6RT6&sz=w800' },
            { id: 11, title: 'Stainless Steel Tory Burch Pendant', price: 570, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1cb2DJ0laOEL9fIRG7D8ysGwOFAvdvij0&sz=w800' },
            { id: 12, title: 'Stainless Steel Golden Handcuff', price: 750, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1bo_YKjdqLfJ-WinJl2G3uHqM4_jKuheS&sz=w800' },
            { id: 13, title: 'Stainless Steel Bold Handcuff', price: 1000, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1YSpv83_5cBdLkvsYIlt6Ve0WfobU25Qj&sz=w800' },
            { id: 14, title: 'Stainless Steel Black Stone Handcuff', price: 1250, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1qRYqbgWy5IWa7W896nwjTnwgNOL9sI2F&sz=w800' },
            { id: 15, title: 'Stainless Steel Bow Handcuff', price: 1000, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1GTkdl8swQQSC728wC2dZEO_ypVZMgnKb&sz=w800' },
            { id: 16, title: 'Stainless Steel Cute Duo Handcuff', price: 650, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1AKhjsKNqbVPpS_DzaTJeOVkeHb-TGOhi&sz=w800' },
            { id: 17, title: 'Stainless Steel Gucci Handcuff', price: 950, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1fYcCceoV58oVjqiJH70SgMK_knPnwn97&sz=w800' },
            { id: 18, title: 'Stainles Steel Watch Style Handcuff', price: 900, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1BFXmBdxNKKzFpV7WtQRveVxIrDa_dbmx&sz=w800' },
            { id: 19, title: 'Stainless Steel Clover Sqaure Handcuff', price: 650, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=19wBeEG_YDE9VDF4gU9fpAUPLpgrSnXwN&sz=w800' },
            { id: 20, title: 'Stainless Steel Verchi Handcuff', price: 800, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=12jhZpsEZH7iatkZtymi_69YlrzvTipT3&sz=w800' },
            { id: 21, title: 'Stainless Steel Clover Handcuff 1 Pcs', price: 900, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1zKFINrBpJC4e4T3NB3HT6qr3oXzAjNgY&sz=w800' },
            { id: 22, title: 'Stainless Steel Golden With Cubic Zzirconia Stones Handcuff', price: 1200, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1_PB8JUZ8kiDqgOKvTaooJopFjEtRt3M_&sz=w800' },
            { id: 23, title: 'Stainless Steel Tulip Bracelet', price: 750, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1OE0gH20kQFlGQFdXQQ7k8Hz0Ox-cFIVr&sz=w800' },
            { id: 24, title: 'Stainless Steel Nose Ring 6mm And 8mm', price: 750, category: 'Rings', image: 'https://drive.google.com/thumbnail?id=1sJjB9gnrHXBRW6khBjLtbYz71B6Gmgh2&sz=w800' },
            { id: 25, title: 'Stainless Steel Snake Chain Butterfly Pendant', price: 700, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=15kxpoIQZkiKk2Y77jSYNLrkEgngWzhqR&sz=w800' },
            { id: 26, title: 'Stainless Steel Swan Duck Set Deal', price: 1550, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1OZ-YuwQnTUxCmbmFxudCoBq1hRkSnCQm&sz=w800' },
            { id: 27, title: 'Stainless Steel Clover Set', price: 1350, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=17wP8OkxctjQdqzBwuXwDgjeADF6CuN8X&sz=w800' },
            { id: 28, title: 'Stainless Steel Green Dial Pendant', price: 700, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1XSqmRzcBHEL5KgPwckwXsC6TeIC0K85Y&sz=w800' },
            { id: 29, title: 'Stainless Steel Classic Green Stone Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1jwO9c7-BOjXXmfFy3xTKrhqi9M64g2Xl&sz=w800' },
            { id: 30, title: 'Stainless Steel Classic Black Stone Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1JzNp5XpCUyDb0W2XzoTu5lzw2UXPLyY8&sz=w800' },
            { id: 31, title: 'Stainless Steel Watch Style Set', price: 2250, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=15CuGljLmdDc0x-SvhXs2--6qRC7IzLlA&sz=w800' },
            { id: 32, title: 'Stainless Steel Double Chain Heart Set', price: 850, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=11yXkjncQIf-Zjf30MOJcozhRQuImPebc&sz=w800' },
            { id: 33, title: 'Stainless Steel Double Style Pendant', price: 800, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=12bbflnvLVRT0YfoRNU4yv2hcfRQ_dJik&sz=w800' },
            { id: 34, title: 'Stainless Steel Double Hoops 1 Pair', price: 750, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1jbmlXG6D6Kx-ZA3oeEf_jbDUaR5fRDbA&sz=w800' },
            { id: 35, title: 'Stainless Steel Black Heart Set', price: 700, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1puZTke5_9JLOyto1tV7G2vjG-RYzpGp2&sz=w800' },
            { id: 36, title: 'Stainless Steel Mini Heart Set Deal', price: 1000, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1gU30YQGjoDtQ46vjLTKq3YkVGr06TEBo&sz=w800' },
            { id: 37, title: 'Stainless Steel Heart Pendant', price: 600, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1c5f-JhA2PTwyNGIV3Nn_iiDPCRLW4HW8&sz=w800' },
            { id: 38, title: 'Stainless Steel Cartier Handcuff', price: 650, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1mTMo_pu7cqNl-UuLyHdr1wxafD4gn8HT&sz=w800' },
            { id: 39, title: 'Stainless Steel Handchain', price: 700, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1OF9fJYcVzGA9WzSPkebLAbO9jKVAstEm&sz=w800' },
            { id: 40, title: 'Stainless Steel Mini White Heart Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1rtYNhObQZgsQKDttPJy1Rni-bfD6a38f&sz=w800' },
            { id: 41, title: 'Stainless Steel Flower Set', price: 600, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1sTgwMy9yAqEf1ttUY2BgL6QPUfKazabC&sz=w800' },
            { id: 42, title: 'Stainless Steel Swan Pendant', price: 550, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1LiURPLouC0OgovM9bhdyXegsmomqGWK6&sz=w800' },
            { id: 43, title: 'Stainless Steel Swan Studs', price: 400, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1-Jm8WlKzzLA_gVPqCBFSMbukbyIQ250l&sz=w800' },
            { id: 44, title: 'Stainless Steel Black Square Ring Size 7', price: 450, category: 'Rings', image: 'https://drive.google.com/thumbnail?id=1r-wm1OQLZkXYCpmr0u4bE-AZO4wGrcjc&sz=w800' },
            { id: 45, title: 'Stainless Steel Bracelet', price: 600, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1P_KESTmlCigfvoavvjYtjMlVsE7H5pIT&sz=w800' },
            { id: 46, title: 'Stainless Steel Snake Bracelet', price: 500, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1NNwFchfwddBA2Ni-x7TdJKjhn5a2oTo_&sz=w800' },
            { id: 47, title: 'Stainless Steel Heart Ankelet', price: 600, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1fVa39TjvhrPHVIeK22PKTMTvoQLdp10W&sz=w800' },
            { id: 48, title: 'Stainless Steel Black Sqaure Set Deal', price: 850, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1emzH2RTkjpanrIfjG4IzW8nqfrUxkAVj&sz=w800' },
            { id: 49, title: 'Stainless Steel Double Layer Bracelet', price: 750, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1-pU7xY2J38QiilypFMpHlr2J9EImTx71&sz=w800' },
            { id: 50, title: 'Stainless Steel White Square Bracelet', price: 700, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1F5OoBvFziCzUed2kD6xXQGZxYEVPS3lB&sz=w800' },
            { id: 51, title: 'Stainless Steel Hoops', price: 450, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1wLucq5tkeBzxw1q_qnL5jNXBqbuhMun9&sz=w800' },
            { id: 52, title: 'Stainless Steel Snake Ring Adjustable', price: 380, category: 'Rings', image: 'https://drive.google.com/thumbnail?id=1nBe-3Y1a0Y56nt4FEouMqYOefiajH0Zx&sz=w800' },
            { id: 53, title: 'Stainless Steel Bold Ring Adjustable', price: 550, category: 'Rings', image: 'https://drive.google.com/thumbnail?id=1p5MdFiiiCYhulRpaKt5uaJFa2_cyaP90&sz=w800' },
            { id: 54, title: 'Stainless Steel Bricks Ring Adjustable', price: 550, category: 'Rings', image: 'https://drive.google.com/thumbnail?id=11TiHJ11Y0CLU0zkdTxg74iGtx-iDJBNR&sz=w800' },
            { id: 55, title: 'Stainless Steel Mini Leafs Handcuff', price: 1100, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1lEy0QucbqHeCcEjj0cTQax5j4wXiTjp5&sz=w800' },
            { id: 56, title: 'Stainless Steel Green Stone Handcuff', price: 1250, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=16ySvK-eu5DpElVzWYtna0zG36HFxNUVD&sz=w800' },
            { id: 57, title: 'Stainless Steel Adjustable Handcuff And Ring', price: 1000, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=19BsDB6vHpmUGZZ3qPn0VSl95WG-JMXGn&sz=w800' },
            { id: 58, title: 'Stainless Steel Sliver Cartier', price: 650, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1Phpdr2THxalNjTv6r2Q5K8Qp8KOf9QQ2&sz=w800' },
            { id: 59, title: 'Stainless Steel Adjustable Handcuff', price: 750, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1QGk69Egy5kFdojEiCz-SefntOAnNx96J&sz=w800' },
            { id: 60, title: 'Stainless Steel Mahroon Mini Heart Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1AVjBQHR4rXw3lFSoqZHL6AaJ4tMuub0a&sz=w800' },
            { id: 61, title: 'Stainless Steel Combo Deal', price: 1200, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=11wdf13aMnxTE_n9rGyiGv4s_2h5_96Vc&sz=w800' },
            { id: 62, title: 'Stainless Steel Three Heart Bracelet', price: 600, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1w6qmkd6X-2Zc48NW2k-oTrBPb7oISP1t&sz=w800' },
            { id: 63, title: 'Stainless Steel Black And White Mini Heart Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1FzZ6Ev4Ms3gkQc58FN72updnJtIXRNrf&sz=w800' },
            { id: 64, title: 'Stainless Steel Adjustable Ring', price: 380, category: 'Rings', image: 'https://drive.google.com/thumbnail?id=19FxfkR4LIEcxGkExvuu2DvAYBVb0Vn4G&sz=w800' },
            { id: 65, title: 'Stainless Steel Combo Deal 3 In 1', price: 1800, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1j0Kpy74KD_uJDwPoDh3BZrlEA9JgyPGZ&sz=w800' },
            { id: 66, title: 'Stainless Steel Golden Clover Set Deal', price: 1500, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1g9YKvxxpWBR_1npakXU3Rlx4uYUKsa5Y&sz=w800' },
            { id: 67, title: 'Stainless Steel White Clover Set Deal', price: 1500, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=18-FW3UP7nzeItwI1NWGosVHi0D1Z220p&sz=w800' },
            { id: 68, title: 'Stainless Steel White Clover Bracelet', price: 550, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=15K6m7ILnM2pv1oKBXEI0P9CbjU2It9hk&sz=w800' },
            { id: 69, title: 'Stainless Steel Multi Clover Bracelet', price: 550, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1-E3XZhJ_X2OMwFpgPxyzP7Bjzv3_5OhT&sz=w800' },
            { id: 70, title: 'Stainless Steel Green Clover Bracelet', price: 550, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1co2FZ_AZ7_2Xb0f0pWYLe6eiQDlLi_7l&sz=w800' },
            { id: 71, title: 'Stainless Steel White Rose Stone Handcuff', price: 700, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1n5Cvz-mGgOAHwcSjJEIdfWWQ9n5WKn2q&sz=w800' },
            { id: 72, title: 'Stainless Steel Chain Bracelet', price: 700, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1fCZC4L7arDD2CtR9_g4b5DmAFKr4EYJX&sz=w800' },
            { id: 73, title: 'Stainless Steel Golden Clover Bracelet', price: 550, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=15m-1bsT5ehnC8c_JlAC7WXjSQjpNQjQM&sz=w800' },
            { id: 74, title: 'Stainless Steel Blue Clover Bracelet', price: 550, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=13RfAyd6o50jPX1Yx9JaUk0WtyHe_5iXh&sz=w800' },
            { id: 75, title: 'Stainless Steel Hania Amir Viral Nose Ring 6mm Size', price: 550, category: 'Rings', image: 'https://drive.google.com/thumbnail?id=1Gk1wx0Nzp0qb554MG2FdlzmbYcXISv8Z&sz=w800' },
            { id: 76, title: 'Stainless Steel Green Stone Pendant', price: 600, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1PsoyKVqXKcLMZ5OPp2W5QkA0ZWeGtRCQ&sz=w800' },
            { id: 77, title: 'Stainless Steel White & Black Clover Bracelet', price: 550, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1Lw-V41yspLdECAgAwG7TRCnQXuGNt0tm&sz=w800' },
            { id: 78, title: 'Stainless Steel White Stone Pendant', price: 600, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1Hw-jJ8WLrBalkcJu3rbsLQdtDb2Ecz7M&sz=w800' },
            { id: 79, title: 'Stainless Steel Black Circle Handcuff', price: 700, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=16xtBwevEQ_6v8j8wkWVeMrGx66t2GeJ5&sz=w800' },
            { id: 80, title: 'Stainless Steel Green Rectangle Stone Handcuff', price: 1250, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=14GY4pnBTERZnNnWV4-p4s5lcSe3VMDyd&sz=w800' },
            { id: 81, title: 'Stainless Steel Watch Style Handcuff', price: 850, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1NRXEqdd_8jOQBxY7e8NfrPON__V_h6IS&sz=w800' },
            { id: 82, title: 'Stainless Steel Clover Set Deal', price: 1500, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1HhL19O4NVkZGg2XUdvxEaZZktEHkt9yK&sz=w800' },
            { id: 83, title: 'Stainless Steel Verchi White Stone Handcuff', price: 1200, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1Kd2dA6RdKfi3i8gReTDlTKkEqjCUrJGf&sz=w800' },
            { id: 84, title: 'Stainless Steel Handcuff Bracelet Combo Deal', price: 1999, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1wr4jgNPxZHyrEL7zUbuOi1QbEbLr9IVd&sz=w800' },
            { id: 85, title: 'Stainless Steel Mini Flower Stone Bracelet', price: 600, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1lCqhuxMTnl4arbxTdq_fW3z3SY5Jgayv&sz=w800' },
            { id: 86, title: 'Stainless Steel Heart Studs', price: 450, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1-9IKDoNV7ZTkuqmI22eQEO3nq7g9uRTs&sz=w800' },
            { id: 87, title: 'Stainless Steel Black Square Pendant', price: 600, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=18_ea_G34rvZMpvEOpnJAFttR-YJ-3avc&sz=w800' },
            { id: 88, title: 'Stainless Steel Heart Set', price: 800, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1P9GakOTMLwK6U3Bt3g4N2YaSR5iAV8ef&sz=w800' },
            { id: 89, title: 'Stainless Steel Heart Set Deal', price: 1100, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1DxNSG8zABX0snNNPCm3iJIPOE4zS9MXD&sz=w800' },
            { id: 90, title: 'Stainless Steel 3 Layer Butterfly Bracelet', price: 650, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1tyP5lz0dOyPcFHnkeuRGxaByjhkCUvhy&sz=w800' },
            { id: 91, title: 'Stainless Steel Double Chain Bracelet', price: 700, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1jdKNdU3EXmr6lcGDx6izIyr2VGgBhZht&sz=w800' },
            { id: 92, title: 'Stainless Steel Double Chain Butterfly Bracelet', price: 750, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1nXheQlsZe3vPnN7m6evytiktEuzlN_pZ&sz=w800' },
            { id: 93, title: 'Stainless Steel Green 2 Chain Bracelet', price: 700, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1aiMilODspj_1QPdgL0EVoe4EOv5qzzgr&sz=w800' },
            { id: 94, title: 'Stainless Steel LV Bracelet & Ankelet', price: 600, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1nrijvEXRvdy6BH00Z2q0SAh0C_rritwM&sz=w800' },
            { id: 95, title: 'Stainless Steel Rotating Sunflower Pendant', price: 750, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=15HNh7Ahrel5Ef2u9H7ZZQfhvuN2qPXoI&sz=w800' },
            { id: 96, title: 'Stainless Steel Elegant Green Stone Bracelet', price: 750, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1fiQycIFHGrnqyS4kp7eCGGZLqYVhtI7q&sz=w800' },
            { id: 97, title: 'Stainless Steel Long Chain Pendant', price: 700, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1hrvktHQ94nwUU8qcj9CWJ_SmYD0gBg9Z&sz=w800' },
            { id: 98, title: 'Stainless Steel Multi Butterfly Pendant', price: 570, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=15-fOdw7D2DD80FyCVMPb3mJUF1-KEhpC&sz=w800' },
            { id: 99, title: 'Stainless Steel Sliver Pendant For Boys', price: 600, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1FZTEy8A-qVh0IIuxwyJ2vcRFeCVAoMGf&sz=w800' },
            { id: 100, title: 'Stainless Steel Double Chain Flower Necklace Set', price: 999, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=15pZS_NnTTtFU8dP87f6_Akpu0p1wXqTL&sz=w800' },
            { id: 101, title: 'Stainless Steel Double Layer Necklace', price: 850, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1TMJq8EwOg5KVMyJ617UknlIPQseYKcud&sz=w800' },
            { id: 102, title: 'Stainless Steel Double Layer Star Necklace', price: 850, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1cco6iiyA28xlV-rVuHXyvWt5j1LlL991&sz=w800' },
            { id: 103, title: 'Stainless Steel Double Layer Heart Necklace Set', price: 999, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=19yBauZIfT_AhYsn6z-U170C8dx21JfNA&sz=w800' },
            { id: 104, title: 'Stainless Steel Sliver Star Pendant', price: 600, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1OOOYG5hVD40iTBXtROyqMTxVnBNq4ExL&sz=w800' },
            { id: 105, title: 'Stainless Steel Sanke Chain Heart Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1JKlhE8EJnhoMIfZxUC53c2NzPR9qlHHt&sz=w800' },
            { id: 106, title: 'Stainles Steel Diamond Necklace', price: 750, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1oFMq-kVGZVbJYE-4reDwegW_1gQG-Z-e&sz=w800' },
            { id: 107, title: 'Stainles Steel Diamond Necklace & Bracelet Deal', price: 1300, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1Ob6U6MbaX9fq6Ngmlopn0gijX7NFDpLK&sz=w800' },
            { id: 108, title: 'Stainles Steel Tree Ankelet', price: 600, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=183Fa3X1PmDHjhwt9j6zN7OZfZe5jDUHR&sz=w800' },
            { id: 109, title: 'Stainless Steel Ankelet', price: 600, category: 'Accessories', image: 'https://drive.google.com/thumbnail?id=1MM_Ob2KeqowBrAlGY8XDHY6Wgw752hAY&sz=w800' },
            { id: 110, title: 'Stainles Steel Diamond Bracelet', price: 650, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1hPKJfGFDGikR9PHJFe6b8ED3b1f5inSc&sz=w800' },
            { id: 111, title: 'Stainless Steel Sliver Heart Bracelet', price: 600, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=15xdeJHxqIC8pqimhVncd4SNF93_oycwn&sz=w800' },
            { id: 112, title: 'Stainless Steel Bow Bracelet', price: 600, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1EradrQMuSfHJyN1GrLq_EUUzdRwBZJ5K&sz=w800' },
            { id: 113, title: 'Stainless Steel White Heart Bracelet', price: 600, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=19zBdICd1rg7iVVv693uiHYZJevlwe6PK&sz=w800' },
            { id: 114, title: 'Stainless Steel Mini Heart Bracelet', price: 600, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1J0vT5S7Wkw_PlDWNQ05SngLJ72O1FmjS&sz=w800' },
            { id: 115, title: 'Aytal Kursi Handcuff Stainless Steel Black Color', price: 1200, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1-ursHjvjlRo9ikjZ10aS1pbhtHLSd2YK&sz=w800' },
            { id: 116, title: 'Aytal Kursi Handcuff Stainless Steel Golden Color', price: 1200, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1dXQ4i2d6tGuIf-koJ8Ds2hiPBUO5Z28X&sz=w800' },
            { id: 117, title: 'Stainless Steel Handcuff', price: 1000, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1LSsxEiIbAH7pZSonrUTurg6802e8_46J&sz=w800' },
            { id: 118, title: 'Stainless Steel Nail Cartier Handcuff', price: 700, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1356Bqlp0IDeK_I6HGPUhdW7SWCnOwbTC&sz=w800' },
            { id: 119, title: 'Stainless Steel Gold Tile Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1uF7ipGoXHqskDcaZg94tvp_iFCDuz0nK&sz=w800' },
            { id: 120, title: 'Stainless Steel Bow Heart Pendant', price: 650, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1ePtdXHdndicNXC4BpRLEqKyBr6VOHRBY&sz=w800' },
            { id: 121, title: 'Stainless Steel Flower Handchain With Adjustable Ring', price: 900, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1mr03DJ8FRWXFJILwe-y5Wdj05YJmk08O&sz=w800' },
            { id: 122, title: 'Stainless Steel Rotating Clover Pendant', price: 750, category: 'Necklaces', image: 'https://drive.google.com/thumbnail?id=1E-8_yrjbwqm7DKCWormt8AQ4z8aGHEOA&sz=w800' },
            { id: 123, title: 'Stainless Steel Mini Golden Hoops', price: 800, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1kPyI9F-XKriE6ooH_NMD2qD50CEQlCk7&sz=w800' },
            { id: 124, title: 'Stainless Steel Mini Sliver Hoops', price: 800, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1yrzoPvRUOIahrya0QHbRObtTZcM7pFh0&sz=w800' },
            { id: 125, title: 'Stainless Steel Mini Stone Hoops', price: 850, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1RXr-3nCbNGQNmbd9Ay5jybs4n6d_C_Oz&sz=w800' },
            { id: 126, title: 'Stainless Steel Guicc Handcuff', price: 900, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1KD5R9iN8dzsMyMp-CGu0Xfauqx2D5f1F&sz=w800' },
            { id: 127, title: 'Stainless Steel LV Handcuff With Stone', price: 1000, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1b0RCLw0OHZyshIZeAGZZUyaZ9Yx7K8ou&sz=w800' },
            { id: 128, title: 'Stainless Steel Mini Star Moon Style Handcuff', price: 1000, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1pdJAT_YErmaajRM6_gk0JQWmVAXMrX2x&sz=w800' },
            { id: 129, title: 'Stainless Steel Leaf Adjustable Handcuff', price: 750, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1BAJOK7n5aTh1HyhoN3Yb_EfSanB4URAH&sz=w800' },
            { id: 130, title: 'Stainless Steel Sliver Pink Pookie Adjustable Ring', price: 450, category: 'Rings', image: 'https://drive.google.com/thumbnail?id=1mwtY6lDqawvUI57gRnfYkxcz4aV3pHq1&sz=w800' },
            { id: 131, title: 'Stainless Steel Mini Clover Stone Handcuff', price: 900, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1yWxpUmSqO5o5epF5kodF2lMiPZUP-j1x&sz=w800' },
            { id: 132, title: 'Stainless Steel Roman Number Stones Handcuff', price: 1150, category: 'Bracelets', image: 'https://drive.google.com/thumbnail?id=1T-voqkvHuXkD1iNZkC6fLg92-6j6r4Bc&sz=w800' },
            { id: 133, title: 'Stainless Steel Double Earring With Chain 1 Pair', price: 750, category: 'Earrings', image: 'https://drive.google.com/thumbnail?id=1azMs3sXnx97rqnyb4zPr4c9izkY48f89&sz=w800' }
        ];
